stages:
  - install
  - build
  - deploy

variables:
  NODE_ENV: production
  # Dossier de build Angular
  BUILD_DIR: dist/Json2pearl/browser
  # Empêche npm d'utiliser le cache global
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

install_dependencies:
  stage: install
  image: node:20
  script:
    - npm ci
    - npm i -g @angular/cli
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h

build_app:
  stage: build
  image: node:20
  script:
    - npm run build
  artifacts:
    paths:
      - $BUILD_DIR/
    expire_in: 1 week
  dependencies:
    - install_dependencies
  only:
    - master

# Déploiement sur GitLab Pages
pages:
  stage: deploy
  image: node:20-alpine
  script:
    - mkdir -p public
    - cp -r $BUILD_DIR/* public/
  artifacts:
    paths:
      - public
  dependencies:
    - build_app
  only:
    - master