stages:          # List of stages for jobs and their order of execution
  - build

build-job:
  stage: build   # Set this job to run in the `build` stage
  image: node:22
  script:
    - npm install
    - npm install @angular/cli@20 --no-save
    - npm run build
  artifacts:
    paths:
      - "build/"