stages:
  - install
  - build
  - deploy

variables:
  NODE_ENV: production
  BUILD_DIR: dist/json2pearl
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

install_dependencies:
  stage: install
  image: node:22
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h

build_app:
  stage: build
  image: node:22
  script:
    - set -e
    - echo "Node version:" && node -v
    - echo "NPM version:" && npm -v
    - echo "Angular CLI version:" && npx ng version
    - npx ng build --configuration production
    - echo "Vérifions le contenu de dist/"
    - ls -R dist || echo "⚠️ Dossier dist non trouvé"
  artifacts:
    paths:
      - $BUILD_DIR/
    expire_in: 1 week
  dependencies:
    - install_dependencies
  only:
    - master

pages:
  stage: deploy
  image: node:22-alpine
  script:
    - mkdir -p public
    - echo "Contenu courant :"
    - ls -R .
    - cp -r $BUILD_DIR/* public/
  artifacts:
    paths:
      - public
  dependencies:
    - build_app
  only:
    - master
